language: python
python:
- 2.7
script: python -m veep
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
  - secure: mAQL7ulCn4nCnRHRAzqEVTD21IIj2IepcCtDEGMgwXcdvaD92rdE9exLGYDabBwPCSChLCBossSW7tdmZNgBpiLG1yYh26Xn5gcbk1oBFeyO5zF7O+2M785aKizUH6sqsCZyJepDRhcrOl6lRRPYeoUETWMbvWU0Hi3P6waLyn49mcH/kr44eGeVkXw772I6H2xjdb7RoHUyN/K2OYufmJBeOPlnLwXEMfPA3JYf2dk8QqVY2JjG2551lybZ/3rfOCB9yWpIh8waKWjfBcYqvei9HhV7+/iHElYgsxludb6c7ZrO/LFad8VIuOACmerqDOB4HKpVEXvJUx6bOwDnNlcj4PoIMuE8BubEWdpZKi8fsacX/cdSDpxFzWqgMUvSHiUAC1zi6F3MVAVNjIaFUIN7rpUerNrl0sgijb0vwPUzBDi0Nt5XRDiIyifxOu0zIZ7C/blfAdypAw9jxt0RnNwn9T8CrEtKP80rCE/uqGo9jTX8e4u0kRPyQ5zNmewWNCGgoX52a0leAu9hkYvlyibMJeesc7di92ED69oMM4hzcheghu/7I0siXi+B9x2ekVrRZLbZbtmhTPXMup4h7srUaS3jjVsVg9CfxdJsPSlxo/fzjf2FGlZ4qWbcKufoABdyN6uiu/p+ATinvEkLp8bE7Gi8anuV0lhCJ18q0kA=
  - secure: Hq9w4J3bPM4z7xR3mjgpth9jYgDNAH89trEsr/fIQ8APLT9DhYxfZsM54raBIEg0WBVHAKFoTroVwP87na/AFMbcJvVpPaN/yL5JT141EE0irXI+xScrrV76N5FBxKHFeeMgNHFnDnojacAhB92W9Q1O8O7KP1pvBUEGyxorH96Ep8grIozyUeL4E0mVV+05srXmO+pd6wIgUHspO9Z54KUADFQFIMzmo/DAebNdyEnDAw6mfU3LwkeleWGRUmLPDTsTRTms9GdNKGUqKdR0a0/PcEXoUEB5cbumn7T0Dy75BCXZ3euUY+SZSi63RY/IJOKQVDudjl8iiNXyKQG7RDrefkTRlzPj4nu1yLMK5zGV3dvFajImjOlAbIQdWHAQuUzL12Aqh5MxsKecuJfFvtC5vEiyhdRqQknxhGc5liO23RtfuO401iGz7R5dTLuWtSDYK5qHL478DaEBXYpwBMTEzV0P1tzE6mgur6sueMvyrQKPXbclDfPdobQvLxRAVCQqUixG21J7/zzJnFjOMg0GlJuktyG/hhLMR06Z/misFtlp3LmOCwOyV7Q/x0AUHrgrft+pGwQTZ6I89XiTfjtdowSRVz4ciaeP1efjz8N8D0nXlyO4oMIm/+NCJF9Dl0sOrT7j/5qOfnRInmw60qlOkMRWFV07vrDy4uV+yCQ=
