language: python
python:
- 2.6
- 2.7
- 3.2
- 3.4

script: python -m veep

notifications:
 email:
  on_success: change
  on_failure: change
 slack:
  on_success: change
  on_failure: change
  secure: W1oAlns14MkxNDfegtA433jIXtzRmKZfgWyUafTCNsVX6xxmCjlHLli1s02tBJkuo5wuJt2zcnEGsuFN5N7J92lKgQZ7JZWO3eQUGIkdkhUZYVzPNwcvV/wCq0shVJzElmE46jDZ+JUucoGqXwPCFWd31YfGS+MRETWBHdVTySg=
